apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-app-deployment
  labels:
    app: enterprise-app
spec:
  replicas: 1
  # --- ADDED: ZERO-DOWNTIME ROLLING UPDATE STRATEGY ---
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       # Allows Kubernetes to spin up 1 extra pod during updates
      maxUnavailable: 0 # Forces Kubernetes to keep all old pods alive until new ones are healthy
  selector:
    matchLabels:
      app: enterprise-app
  template:
    metadata:
      labels:
        app: enterprise-app
    spec:
      containers:
      - name: python-app
        image: sjcesharathkumar/app:latest 
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "50Mi"
            cpu: "25m"
          limits:
            memory: "150Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10