apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-app-deployment
  labels:
    app: enterprise-core
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: enterprise-core
  template:
    metadata:
      labels:
        app: enterprise-core
    spec:
      containers:
      - name: python-app
        image: sjcesharathkumar/enterprise-core-platform:latest
        imagePullPolicy: Always  
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "50Mi"
            cpu: "25m"
          limits:
            memory: "150Mi"
            cpu: "50m"
        envFrom:
        - configMapRef:
            name: enterprise-app-config

        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10