apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-app-deployment
  labels:
    app: enterprise-app
spec:
  replicas: 2 # Spreads across both available AZ worker nodes for high availability
  selector:
    matchLabels:
      app: enterprise-app
  template:
    metadata:
      labels:
        app: enterprise-app
    spec:
      containers:
      - name: python-app
        image: python:3.9-slim # A lightweight Python image to protect your memory footprint
        command: ["python", "-m", "http.server", "8000"] # Spins up a quick built-in web server for testing
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-app-service
spec:
  type: LoadBalancer # Tells AWS to provision a real cloud Load Balancer so you can visit your app via the web browser
  selector:
    app: enterprise-app
  ports:
    - protocol: TCP
      port: 80      # The public web port you will access in your browser
      targetPort: 8000 # The internal port your container is listening on